apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  distribution:
    version: ${K8S_VERSION}
  topology:
    controlPlane:
      count: 1                          # 1 control plane nodes
      class: best-effort-xsmall         # Best effort extra small class
      storageClass: kubernetes          # Specific storage class for control plane
    workers:
      count: 3                          # 3 worker nodes
      class: best-effort-xsmall         # Best effort extra small class
      storageClass: kubernetes          # Specific storage class for workers
  settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.51.100.0/12"] # Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/16"]    # Cannot overlap with Supervisor Cluster
    storage:
      classes: ["kubernetes"]           # Named PVC storage classes
      defaultClass: kubernetes          # Default PVC storage class