apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: ${NAME}
  namespace: ${NAMESPACE}
spec:
  distribution:
    version: ${K8S_VERSION}
  topology:
    controlPlane:
      count: ${CP_COUNT}                          # 1 control plane nodes
      class: ${CP_VM_CLASS}         # Best effort extra small class
      storageClass: ${CP_STORAGE_CLASS}          # Specific storage class for control plane
    workers:
      count: ${W_COUNT}                          # 3 worker nodes
      class: ${W_VM_CLASS}         # Best effort extra small class
      storageClass: ${W_STORAGE_CLASS}          # Specific storage class for workers
  settings:
    network:
      cni:
        name: ${CNI}
      services:
        cidrBlocks: ${SERVICE_CIDR} # Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ${POD_CIDR}    # Cannot overlap with Supervisor Cluster
    storage:
      classes: ${STORAGE_CLASSES}           # Named PVC storage classes
      defaultClass: ${DEFAULT_STORAGE_CLASS}          # Default PVC storage class