apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:demo@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo
- context:
    cluster: 172.17.0.1
    namespace: demo2
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo2
current-context: 10.0.10.30
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIyNzc0MDc5LCJpYXQiOjE2MjI3MzgwNzksImp0aSI6ImNhZGM3M2JiLTBhNWEtNGQ2NC1iNTIzLWFkMDllZTc0OGIwMiIsInVzZXJuYW1lIjoiZGVtbyJ9.ek1rfzK21rmESLjg_Z5SwkBR5dpjMO2Mtvs6r6LgDshhtlLu5lHXrLV5m-SRHLSOtsuvQBgb2m8ENmWLypIDEPBzHPnEhKbNgen9mSRa2Geba9NcMl6hB_RQsyXrmE3G6xFssUGz9euTgr7d7p7uXGGwHqXGAO4G0Bn4g5tuNqieFCaExpxEtoXAeuepA1sAvfemGYSeH0qt8Hx7wc4_tIytGdXb-kxy8vS5KncZX-Y3f1F0rhueHQ3XIsamkD2SPR6DltHc6UFHMMEKob6SPJJUqiuew8WwY0yGrXKyMDZRUgyKQzpTghl2Xv4Hi4d7qE9ckd9QY9QRIKFfxeXs_w
- name: wcp:172.17.0.1:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjIyNzc0MDgwLCJpYXQiOjE2MjI3MzgwODAsImp0aSI6IjkwMjFlNTEyLTA2MDItNGEwNC1iZmVjLWFhNmFhNzc1ZDM5ZiIsInVzZXJuYW1lIjoiZGVtbyJ9.VXgBzex2t3YdIQDZz_RBSX-xl3k_p6kCGfFpynFIqQe64wZSwZs2vtlnC6raS5LfJa1QQR1jI8CiM--TJvkLOXhXEWPCwoZw0izWD5w-KiO2tSbGl8-NQ1IMlQv9O3CKw4DDYCkX0TQPk9sUxUMflO1H3s5laxxgD1LyjFq5wykSOcgM9agBoZfloLFPcTPWsKqAIEq4GQy-yP00Wv9A0TKdEKHmrWGz1UiBZT8WkvDvzugMKx9YyyT82BG6PWD_gajkooY2klmCydUBrT-X6pHPDwsQUIxyHypvIxaiDcTOKLf054FmeKcaEW5N2TnDGWnStcKu0BAI3mLjkNslNA
