apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.10.30:6443
  name: 10.0.10.30
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.17.0.1:6443
  name: 172.17.0.1
contexts:
- context:
    cluster: 10.0.10.30
    user: wcp:10.0.10.30:demo@vsphere.local
  name: 10.0.10.30
- context:
    cluster: 172.17.0.1
    namespace: demo
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo
- context:
    cluster: 172.17.0.1
    namespace: demo2
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo2
- context:
    cluster: 172.17.0.1
    namespace: demo3
    user: wcp:172.17.0.1:demo@vsphere.local
  name: demo3
current-context: 10.0.10.30
kind: Config
preferences: {}
users:
- name: wcp:10.0.10.30:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjI0NDkwMTE2LCJpYXQiOjE2MjQ0NTQxMTYsImp0aSI6IjE2ZWUyMDBkLWNlMzAtNDBmZC1iMjlkLWY3M2I4NjgxNmI1ZiIsInVzZXJuYW1lIjoiZGVtbyJ9.MS4op7gYIBO30kM8mfNJtylY_G2l4a5ZeYmLDxNL8_v74O2DtRomsZEjkRoxJzxjwUlTuofgX7r7tL2KT3CbOAWBWNE4c3A8F2xCBP11M6kU8RjN5fPTmArVuGSa9ACtI2W2G3OA5gcxdLQ_FrttkGtKjfeI1zUyjJH2tVhYDQNPjnospsM56G-MRv36NHnKBZND6e93vSPBs5XkLIUAE3MicVoJzJLGAzPBRz9jdAEqC1iWhhmpVUDo0kawYJrFhkN5XzbkVbMQ9hcS_drDZU86JwYYv8pKCGIb4aNmRQlM87p1ZCzx3YmfpiKAfwC0O3HA6lzEL9CgzzMjIo3qjg
- name: wcp:172.17.0.1:demo@vsphere.local
  user:
    token: eyJraWQiOiIyMDgxOEMxRTIwNzcwRDY4RDdCMzdDREIxQTRCRjlCNjYxRUFGNjAyIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkZW1vQHZzcGhlcmUubG9jYWwiLCJhdWQiOiJ2bXdhcmUtdGVzOnZjOnZuczprOHMiLCJkb21haW4iOiJ2c3BoZXJlLmxvY2FsIiwiaXNzIjoiaHR0cHM6XC9cLzEwLjAuMTAuMTBcL29wZW5pZGNvbm5lY3RcL3ZzcGhlcmUubG9jYWwiLCJncm91cF9uYW1lcyI6WyJMaWNlbnNlU2VydmljZS5BZG1pbmlzdHJhdG9yc0B2c3BoZXJlLmxvY2FsIiwiQWRtaW5pc3RyYXRvcnNAdnNwaGVyZS5sb2NhbCIsIkV2ZXJ5b25lQHZzcGhlcmUubG9jYWwiLCJTeXN0ZW1Db25maWd1cmF0aW9uLkFkbWluaXN0cmF0b3JzQHZzcGhlcmUubG9jYWwiXSwiZXhwIjoxNjI0NDkwMTE3LCJpYXQiOjE2MjQ0NTQxMTcsImp0aSI6IjI4Mzg2YmVkLWFiNjUtNGE1NC04MzhkLWM3OGY2YzQ1NzEwYSIsInVzZXJuYW1lIjoiZGVtbyJ9.J7ipBBGuktEgsL-VNVFBTWxSUpysOWvGnAAMxuE5vSPgtqD3PeTUIWGAq9basSII81HEg_s1Af9S7VeFqpWZv8IOIwmVKqu7EP1xeM0Ov9MoBmyXdfa8671blY282EPmmD9ZUbzCZSInm8fnVouOI-vCjjT54qo-JMbZyRaeK4NDg3EuzJoZ30lf_HRPSX7w5ZktSy8ilJL-3chDLKPC0koZrq6FUXqYejZXQ4XIoKWbJHVgerkB2mRgEU8QbpJ2hge3BY--2qdKpr1dKCjw9Mpmr-hdv1ARbFkh1cVzb-c1mdTdJ2tXYEPetwEv_PoXj37CkhTkB3ZbX3GEkqXquw
